# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 06:28
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('map', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('pic_list', django_mysql.models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancelledOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_cnt', models.IntegerField(default=0)),
                ('total_traveler_cnt', models.IntegerField(default=0)),
                ('total_guide_day', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2)),
                ('guide_type', models.IntegerField(null=True)),
                ('guide_theme', models.IntegerField(null=True)),
                ('max_traveler_cnt', models.IntegerField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('license', models.BooleanField(default=False)),
                ('is_local', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=True)),
                ('guide_location', django_mysql.models.JSONField(default=dict, null=True)),
                ('off_day', django_mysql.models.JSONField(default=dict, null=True)),
                ('career', django_mysql.models.JSONField(default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('etc', models.CharField(max_length=300)),
                ('travel_period', django_mysql.models.JSONField(default=dict, null=True)),
                ('trans_info', django_mysql.models.JSONField(default=dict, null=True)),
                ('accom_template', django_mysql.models.JSONField(default=dict, null=True)),
                ('guide_template', django_mysql.models.JSONField(default=dict, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(null=True)),
                ('picture', models.CharField(max_length=200)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_id', models.IntegerField(null=True)),
                ('to_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(max_length=11, null=True)),
                ('is_guide', models.BooleanField(default=False)),
                ('delete_reason', models.IntegerField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2)),
                ('nationality', models.CharField(max_length=40, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.NullBooleanField()),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('delete_reason_optional', models.CharField(max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('content', models.TextField(null=True)),
                ('writer_id', models.IntegerField(null=True)),
                ('receiver_id', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=100)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.GuideOffer')),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', django_mysql.models.JSONField(default=dict, null=True)),
                ('travel_begin_at', models.DateField(null=True)),
                ('travel_end_at', models.DateField(null=True)),
                ('age_group', django_mysql.models.JSONField(default=dict, null=True)),
                ('trans_type', models.IntegerField(null=True)),
                ('trans_via', models.IntegerField(null=True)),
                ('trans_class', models.IntegerField(null=True)),
                ('trans_comment', models.CharField(max_length=200)),
                ('accom_location', models.IntegerField(null=True)),
                ('accom_location_optional', models.CharField(max_length=100, null=True)),
                ('accom_type', models.IntegerField(null=True)),
                ('accom_comment', models.CharField(max_length=100)),
                ('start_time', models.IntegerField(null=True)),
                ('end_time', models.IntegerField(null=True)),
                ('landmark', models.CharField(max_length=200)),
                ('theme', models.IntegerField(null=True)),
                ('local_trans', models.CharField(max_length=200)),
                ('guide_type', models.IntegerField(null=True)),
                ('importance', models.IntegerField(null=True)),
                ('cost', models.IntegerField(null=True)),
                ('published', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserRequest'),
        ),
        migrations.AddField(
            model_name='cost',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.GuideOffer'),
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.GuideOffer'),
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide'),
        ),
    ]
