# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:16
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import redactor.fields


class Migration(migrations.Migration):

    replaces = [('webapp', '0001_initial'), ('webapp', '0002_auto_20170313_1603'), ('webapp', '0003_userrequest_additional_request'), ('webapp', '0002_auto_20170313_0205'), ('webapp', '0004_merge_20170314_1148'), ('webapp', '0005_auto_20170316_1948'), ('webapp', '0006_auto_20170316_2101'), ('webapp', '0007_auto_20170317_1453'), ('webapp', '0008_auto_20170317_1458'), ('webapp', '0007_auto_20170317_1248'), ('webapp', '0008_auto_20170317_1343'), ('webapp', '0009_merge_20170317_1508'), ('webapp', '0010_auto_20170318_0210'), ('webapp', '0011_auto_20170318_0252'), ('webapp', '0012_auto_20170318_0617'), ('webapp', '0013_auto_20170319_0134'), ('webapp', '0014_auto_20170320_1432'), ('webapp', '0015_auto_20170321_1151'), ('webapp', '0016_auto_20170321_1723'), ('webapp', '0014_auto_20170320_2111'), ('webapp', '0017_merge_20170321_2318'), ('webapp', '0018_auto_20170322_0433'), ('webapp', '0018_auto_20170322_0120'), ('webapp', '0019_merge_20170322_0448'), ('webapp', '0020_auto_20170322_0541'), ('webapp', '0021_auto_20170322_0618'), ('webapp', '0022_auto_20170322_1854'), ('webapp', '0023_auto_20170323_0209'), ('webapp', '0024_auto_20170325_0325'), ('webapp', '0025_auto_20170325_1710'), ('webapp', '0026_auto_20170326_0203'), ('webapp', '0027_auto_20170326_2156'), ('webapp', '0028_auto_20170327_1658'), ('webapp', '0029_guideoffer_published'), ('webapp', '0030_auto_20170329_1813'), ('webapp', '0031_auto_20170330_2210'), ('webapp', '0031_auto_20170330_1453'), ('webapp', '0032_merge_20170330_2216')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('map', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True, null=True)),
                ('pic_list', django_mysql.models.JSONField(default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CancelledOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_cnt', models.IntegerField(default=0)),
                ('total_traveler_cnt', models.IntegerField(default=0)),
                ('total_guide_day', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2)),
                ('guide_type', models.IntegerField(null=True)),
                ('guide_theme', models.IntegerField(null=True)),
                ('max_traveler_cnt', models.IntegerField(null=True)),
                ('introduction', models.TextField(null=True)),
                ('license', models.BooleanField(default=False)),
                ('is_local', models.BooleanField(default=False)),
                ('activated', models.BooleanField(default=True)),
                ('guide_location', django_mysql.models.JSONField(default=dict, null=True)),
                ('off_day', django_mysql.models.JSONField(default=dict, null=True)),
                ('career', django_mysql.models.JSONField(default=dict, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GuideOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('etc', models.CharField(max_length=300)),
                ('travel_period', django_mysql.models.JSONField(default=dict, null=True)),
                ('trans_info', django_mysql.models.JSONField(default=dict, null=True)),
                ('accom_template', django_mysql.models.JSONField(default=dict, null=True)),
                ('guide_template', django_mysql.models.JSONField(default=dict, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='GuideTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_templates', to='webapp.Guide')),
                ('photo', models.ImageField(upload_to='guide_photos/%Y/%m/%d')),
                ('overwritten', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GuideLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(blank=True, max_length=11)),
                ('is_guide', models.BooleanField(default=False)),
                ('delete_reason', models.IntegerField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2)),
                ('nationality', models.CharField(blank=True, max_length=40)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('photo', models.ImageField(default='profile/2017_03_22/2__15_12_33_307511.jpg', upload_to='profile/%Y_%m_%d')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('delete_reason_optional', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('mail_certified', models.BooleanField(default=False)),
                ('phone_certified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', django_mysql.models.JSONField(default=dict, null=True)),
                ('travel_begin_at', models.DateField(blank=True, null=True)),
                ('travel_end_at', models.DateField(blank=True, null=True)),
                ('age_group', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('trans_type', models.IntegerField(blank=True, default=0)),
                ('trans_via', models.IntegerField(blank=True, default=0)),
                ('trans_class', models.IntegerField(blank=True, default=0)),
                ('trans_comment', models.CharField(blank=True, max_length=200)),
                ('accom_location', models.IntegerField(blank=True, default=0)),
                ('accom_location_optional', models.CharField(blank=True, max_length=100, null=True)),
                ('accom_type', models.IntegerField(blank=True, default=0)),
                ('accom_comment', models.CharField(blank=True, max_length=100)),
                ('start_time', models.IntegerField(blank=True, default=0)),
                ('end_time', models.IntegerField(blank=True, default=0)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('theme', models.IntegerField(blank=True, default=0)),
                ('local_trans', models.IntegerField(blank=True, default=0)),
                ('guide_type', models.IntegerField(blank=True, default=0)),
                ('importance', models.IntegerField(blank=True, default=0)),
                ('cost', models.IntegerField(blank=True, default=0)),
                ('published', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('additional_request', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserRequest'),
        ),
        migrations.AddField(
            model_name='cost',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='webapp.GuideOffer'),
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel', to='webapp.GuideOffer'),
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accom_templates', to='webapp.Guide'),
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guideoffer',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.Guide'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='career',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_location',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_theme',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='max_traveler_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='off_day',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='guideoffer',
            name='etc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.RemoveField(
            model_name='accomtemplate',
            name='map',
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accomtemplate',
            name='address',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=63, size=3),
        ),
        migrations.AlterField(
            model_name='accomtemplate',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='accomtemplate',
            name='pic_list',
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=300)),
                ('writer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.GuideOffer')),
            ],
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='cost',
            name='type',
        ),
        migrations.AddField(
            model_name='cost',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='GuideReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('content', redactor.fields.RedactorField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_review', to='webapp.GuideOffer')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
                ('write_date', models.DateField(default=datetime.date(2017, 3, 30))),
            ],
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('content', redactor.fields.RedactorField(verbose_name='Content')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='webapp.GuideOffer')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('write_date', models.DateField(default=datetime.date(2017, 3, 30))),
            ],
        ),
        migrations.AddField(
            model_name='guidelike',
            name='request',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webapp.UserRequest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='photo',
            field=django_mysql.models.ListTextField(models.CharField(max_length=100), size=None),
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='overwritten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guideoffer',
            name='trans_info',
            field=models.CharField(max_length=500),
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guide',
            name='appeal',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='certificate',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guide',
            name='essay',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='guide',
            name='experience',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='is_thru',
            field=models.BooleanField(default=False, verbose_name='스루 가이드'),
        ),
        migrations.AddField(
            model_name='guide',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guide',
            name='real_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='guide',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name='현지 가이드'),
        ),
    ]
