# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-05 08:51
from __future__ import unicode_literals

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='accom_photos/%Y_%m_%d')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccomTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=63, size=3)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('content', models.TextField(blank=True)),
                ('type_id', models.IntegerField(default=0)),
                ('overwritten', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CancelledOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.IntegerField(null=True)),
                ('reason', models.CharField(max_length=500)),
                ('is_completed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=300)),
                ('writer', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('info', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_cnt', models.IntegerField(default=0)),
                ('total_traveler_cnt', models.IntegerField(default=0)),
                ('total_guide_day', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2)),
                ('guide_type', models.IntegerField(blank=True, null=True)),
                ('guide_theme', models.IntegerField(blank=True, null=True)),
                ('max_traveler_cnt', models.IntegerField(blank=True, null=True)),
                ('introduction', models.TextField(blank=True)),
                ('license', models.BooleanField(default=False)),
                ('is_thru', models.BooleanField(default=False, verbose_name='스루 가이드')),
                ('is_local', models.BooleanField(default=False, verbose_name='현지 가이드')),
                ('activated', models.BooleanField(default=False)),
                ('guide_location', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('guide_country', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('guide_city', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('off_day', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('career', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('real_name', models.TextField(default='')),
                ('certificate', django_mysql.models.JSONField(blank=True, default=dict)),
                ('appeal', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('essay', models.TextField(default='')),
                ('experience', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('is_volunteer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuideAdjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='수취인 이름*')),
                ('bank', models.TextField(verbose_name='은행 이름*')),
                ('account_num', models.TextField(verbose_name='계좌번호 (유럽은행의 경우 IBAN CODE를 적어주세요)*')),
                ('swift_bic_code', models.TextField(blank=True, default='', verbose_name='SWIFT BIC CODE (해외 계좌일 경우)')),
                ('branch', models.TextField(blank=True, default='', verbose_name='은행 지점명 (해외 계좌일 경우)')),
                ('addr', models.TextField(blank=True, default='', verbose_name='수취인 주소 (해외 계좌일 경우)')),
                ('routing_num', models.TextField(blank=True, default='', verbose_name='Routing Number (미국 은행일 경우)')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjust', to='webapp.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuideLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuideOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('etc', models.CharField(blank=True, max_length=300)),
                ('travel_period', django_mysql.models.JSONField(default=dict, null=True)),
                ('trans_info', models.CharField(max_length=500)),
                ('accom_template', django_mysql.models.JSONField(default=dict, null=True)),
                ('guide_template', django_mysql.models.JSONField(default=dict, null=True)),
                ('is_canceled', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('adjust_requested_at', models.DateField(null=True)),
                ('adjust_done_at', models.DateField(null=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuideReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('content', redactor.fields.RedactorField(verbose_name='Content')),
                ('write_date', models.DateField(default=datetime.date(2017, 4, 5))),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_review', to='webapp.GuideOffer')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuideTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True)),
                ('photo', models.ImageField(upload_to='guide_photos/%Y/%m/%d')),
                ('overwritten', models.BooleanField(default=False)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_templates', to='webapp.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.ImageField(upload_to='journal/%Y_%m_%d')),
                ('content', redactor.fields.RedactorField(verbose_name='Content')),
                ('write_date', models.DateField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='webapp.GuideOffer')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_num', models.CharField(blank=True, max_length=11)),
                ('is_guide', models.BooleanField(default=False)),
                ('delete_reason', models.IntegerField(null=True)),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=2)),
                ('nationality', models.CharField(blank=True, max_length=40)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('photo', models.ImageField(default='profile/2017_03_22/2__15_12_33_307511.jpg', upload_to='profile/%Y_%m_%d')),
                ('deleted_at', models.DateTimeField(null=True)),
                ('delete_reason_optional', models.CharField(blank=True, max_length=100)),
                ('mail_certified', models.BooleanField(default=False)),
                ('phone_certified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', django_mysql.models.JSONField(default=dict, null=True)),
                ('travel_begin_at', models.DateField(blank=True, null=True)),
                ('travel_end_at', models.DateField(blank=True, null=True)),
                ('age_group', django_mysql.models.JSONField(blank=True, default=dict, null=True)),
                ('trans_type', models.IntegerField(blank=True, default=0)),
                ('trans_via', models.IntegerField(blank=True, default=0)),
                ('trans_class', models.IntegerField(blank=True, default=0)),
                ('trans_comment', models.CharField(blank=True, max_length=200)),
                ('accom_location', models.IntegerField(blank=True, default=0)),
                ('accom_location_optional', models.CharField(blank=True, max_length=100, null=True)),
                ('accom_type', models.IntegerField(blank=True, default=0)),
                ('accom_comment', models.CharField(blank=True, max_length=100)),
                ('start_time', models.IntegerField(blank=True, default=0)),
                ('end_time', models.IntegerField(blank=True, default=0)),
                ('landmark', models.CharField(blank=True, max_length=200)),
                ('theme', models.IntegerField(blank=True, default=0)),
                ('local_trans', models.IntegerField(blank=True, default=0)),
                ('guide_type', models.IntegerField(blank=True, default=0)),
                ('importance', models.IntegerField(blank=True, default=0)),
                ('cost', models.IntegerField(blank=True, default=0)),
                ('published', models.BooleanField(default=True)),
                ('additional_request', models.CharField(blank=True, max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('content', redactor.fields.RedactorField(verbose_name='Content')),
                ('write_date', models.DateField(default=datetime.date(2017, 4, 5))),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to='webapp.GuideOffer')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserRequest'),
        ),
        migrations.AddField(
            model_name='guidelike',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserRequest'),
        ),
        migrations.AddField(
            model_name='cost',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='webapp.GuideOffer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='webapp.GuideOffer'),
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel', to='webapp.GuideOffer'),
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accom_templates', to='webapp.Guide'),
        ),
        migrations.AddField(
            model_name='accomphoto',
            name='accom_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accom_photos', to='webapp.AccomTemplate'),
        ),
    ]
