# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=100)),
                ('receiver', models.CharField(max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_comment', models.CharField(max_length=200)),
                ('accom_location_optional', models.CharField(max_length=100, null=True)),
                ('accom_comment', models.CharField(max_length=100)),
                ('landmark', models.CharField(max_length=200)),
                ('local_trans', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
