# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAdjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('bank', models.TextField()),
                ('account_num', models.TextField()),
                ('swift_bic_code', models.TextField(blank=True, default='')),
                ('branch', models.TextField(blank=True, default='')),
                ('addr', models.TextField(blank=True, default='')),
                ('routing_num', models.TextField(blank=True, default='')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide')),
            ],
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 31)),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 31)),
        ),
    ]
