# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 05:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
    ]
