# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170313_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='additional_request',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
