# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 04:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_review_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelledOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GuideOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('etc', models.CharField(max_length=300)),
                ('is_canceled', models.BooleanField(default=False)),
                ('guide_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.UserRequest')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='cancelledoffer',
            name='offer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.GuideOffer'),
        ),
    ]
