# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-14 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20170313_0205'),
        ('webapp', '0003_userrequest_additional_request'),
    ]

    operations = [
    ]
