# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20170331_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideoffer',
            name='adjust_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='adjust_requested_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='guideadjust',
            name='account_num',
            field=models.TextField(verbose_name='계좌번호 (유럽은행의 경우 IBAN CODE를 적어주세요)*'),
        ),
        migrations.AlterField(
            model_name='guideadjust',
            name='addr',
            field=models.TextField(blank=True, default='', verbose_name='수취인 주소 (해외 계좌일 경우)'),
        ),
        migrations.AlterField(
            model_name='guideadjust',
            name='branch',
            field=models.TextField(blank=True, default='', verbose_name='은행 지점명 (해외 계좌일 경우)'),
        ),
        migrations.AlterField(
            model_name='guideadjust',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjust', to='webapp.Guide'),
        ),
        migrations.AlterField(
            model_name='guideadjust',
            name='routing_num',
            field=models.TextField(blank=True, default='', verbose_name='Routing Number (미국 은행일 경우)'),
        ),
        migrations.AlterField(
            model_name='guideadjust',
            name='swift_bic_code',
            field=models.TextField(blank=True, default='', verbose_name='SWIFT BIC CODE (해외 계좌일 경우)'),
        ),
    ]
