# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20170331_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideoffer',
            name='adjust_done',
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='adjust_done_at',
            field=models.DateField(null=True),
        ),
    ]
