# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_merge_20170314_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='webapp.GuideOffer'),
        ),
    ]
