# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170227_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guide',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.User'),
        ),
    ]
