# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170331_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guideadjust',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='guideoffer',
            name='adjust_done_at',
        ),
        migrations.RemoveField(
            model_name='guideoffer',
            name='adjust_requested_at',
        ),
        migrations.DeleteModel(
            name='GuideAdjust',
        ),
    ]
