# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20170316_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cost',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='webapp.GuideOffer'),
        ),
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webapp.GuideOffer'),
        ),
    ]
