# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170316_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelledoffer',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guideoffer',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='webapp.UserRequest'),
        ),
    ]
