# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170331_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideAdjust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='수취인 이름*')),
                ('bank', models.TextField(verbose_name='은행 이름*')),
                ('account_num', models.TextField(verbose_name='계좌번호 (유럽은행의 경우 IBAN CODE를 적어주세요)*')),
                ('swift_bic_code', models.TextField(blank=True, default='', verbose_name='SWIFT BIC CODE (해외 계좌일 경우)')),
                ('branch', models.TextField(blank=True, default='', verbose_name='은행 지점명 (해외 계좌일 경우)')),
                ('addr', models.TextField(blank=True, default='', verbose_name='수취인 주소 (해외 계좌일 경우)')),
                ('routing_num', models.TextField(blank=True, default='', verbose_name='Routing Number (미국 은행일 경우)')),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjust', to='webapp.Guide')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='adjust_done_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='guideoffer',
            name='adjust_requested_at',
            field=models.DateField(null=True),
        ),
    ]
