# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 03:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20170316_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='from_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='like',
            name='to_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide'),
        ),
        migrations.AlterField(
            model_name='review',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide'),
        ),
        migrations.AlterField(
            model_name='review',
            name='writer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
