# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 04:43
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20170317_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='to_id',
            new_name='guide',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='from_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='guide',
            name='career',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_location',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_theme',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='guide_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='introduction',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='max_traveler_cnt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='off_day',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='delete_reason_optional',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=models.CharField(blank=True, max_length=11),
        ),
        migrations.AlterField(
            model_name='review',
            name='receiver_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='writer_id',
            field=models.IntegerField(),
        ),
    ]
