# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 06:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20170317_1458'),
        ('webapp', '0008_auto_20170317_1343'),
    ]

    operations = [
    ]
