# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20170403_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidereview',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='thumbnail',
            field=models.ImageField(upload_to='journal/%Y_%m_%d'),
        ),
    ]
