# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_merge_20170317_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mail_certified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_certified',
            field=models.BooleanField(default=False),
        ),
    ]
