# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20170318_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelledoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancel', to='webapp.GuideOffer'),
        ),
    ]
