# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 21:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0011_auto_20170318_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='writer_id',
        ),
        migrations.AddField(
            model_name='review',
            name='guide',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='webapp.Guide'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guideoffer',
            name='etc',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=redactor.fields.RedactorField(),
        ),
    ]
