# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-18 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20170318_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidetemplate',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
