# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 09:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20170405_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='importance_optional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 4, 6)),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='accom_location_optional',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 4, 6)),
        ),
    ]
