# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20170319_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomtemplate',
            name='map',
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='accomtemplate',
            name='address',
            field=django_mysql.models.ListCharField(models.CharField(max_length=20), max_length=63, size=3),
        ),
        migrations.AlterField(
            model_name='accomtemplate',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accomtemplate',
            name='pic_list',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
