# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20170319_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(null=True),
        ),
    ]
