# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-06 12:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20170406_2126'),
        ('webapp', '0014_auto_20170406_1846'),
    ]

    operations = [
    ]
