# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_auto_20170321_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cost',
            name='type',
        ),
        migrations.AddField(
            model_name='cost',
            name='type_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cost',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
