# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-08 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20170409_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guidealarm',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='useralarm',
            name='sender',
        ),
    ]
