# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_auto_20170322_0120'),
        ('webapp', '0018_auto_20170322_0433'),
    ]

    operations = [
    ]
