# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 20:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_merge_20170322_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidereview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 22)),
        ),
        migrations.AddField(
            model_name='userreview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 22)),
        ),
    ]
