# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 09:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_auto_20170410_1721'),
        ('webapp', '0020_auto_20170410_1728'),
    ]

    operations = [
    ]
