# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_merge_20170410_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
