# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-22 09:54
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_auto_20170322_0618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreview',
            name='content',
            field=redactor.fields.RedactorField(verbose_name='Content'),
        ),
    ]
