# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_auto_20170410_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
