# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 05:45
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_auto_20170411_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='cities',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='countries',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='landmark',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
