# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-25 17:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20170325_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidereview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 26)),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='accom_location',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='accom_type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='cost',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='end_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='guide_type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='importance',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='local_trans',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='start_time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='theme',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='trans_class',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='trans_type',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='trans_via',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 26)),
        ),
    ]
