# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-11 05:53
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_auto_20170411_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='cities',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='countries',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
