# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 07:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_auto_20170326_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccomPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='accom_photos/%Y/%m/%d')),
            ],
        ),
        migrations.AddField(
            model_name='accomtemplate',
            name='overwritten',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guidetemplate',
            name='overwritten',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guideoffer',
            name='trans_info',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 27)),
        ),
        migrations.AlterField(
            model_name='guidetemplate',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_templates', to='webapp.Guide'),
        ),
        migrations.AlterField(
            model_name='guidetemplate',
            name='photo',
            field=models.ImageField(upload_to='guide_photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 27)),
        ),
        migrations.AddField(
            model_name='accomphoto',
            name='accom_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accom_photos', to='webapp.AccomTemplate'),
        ),
    ]
