# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_auto_20170327_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideoffer',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
