# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 09:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0029_guideoffer_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accomphoto',
            name='accom_template',
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 29)),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 29)),
        ),
        migrations.DeleteModel(
            name='AccomPhoto',
        ),
    ]
