# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 13:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_auto_20170329_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='appeal',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='certificate',
            field=django_mysql.models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guide',
            name='essay',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='guide',
            name='experience',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='guide',
            name='is_thru',
            field=models.BooleanField(default=False, verbose_name='스루 가이드'),
        ),
        migrations.AddField(
            model_name='guide',
            name='is_volunteer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guide',
            name='real_name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='guide',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guide',
            name='is_local',
            field=models.BooleanField(default=False, verbose_name='현지 가이드'),
        ),
        migrations.AlterField(
            model_name='guidereview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 30)),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='write_date',
            field=models.DateField(default=datetime.date(2017, 3, 30)),
        ),
    ]
