# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 07:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_auto_20170418_0122'),
        ('webapp', '0032_auto_20170418_0108'),
    ]

    operations = [
    ]
