# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-24 07:58
from __future__ import unicode_literals

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_merge_20170424_1658'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userposthit',
            name='post',
        ),
        migrations.AddField(
            model_name='userpost',
            name='hit_user_id',
            field=django_mysql.models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.DeleteModel(
            name='UserPostHit',
        ),
    ]
