# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-25 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0033_merge_20170424_1511'),
        ('webapp', '0034_auto_20170424_1658'),
    ]

    operations = [
    ]
